// src/hooks/useSpotifyAuth.ts

import { Buffer } from 'buffer';
import * as AuthSession from 'expo-auth-session';
import { makeRedirectUri } from 'expo-auth-session';
import * as SecureStore from 'expo-secure-store';
import { useEffect, useMemo, useState } from 'react';
import { API_URL, JWT_KEY } from '../src/config';

global.Buffer = global.Buffer || Buffer;

const clientId = '853b778ca3c241eabce8deda5b5fe5a4';
const redirectUri = makeRedirectUri({ scheme: 'monapp', path: 'home' });
const scopes = [
  'user-read-email',
  'user-read-private',
  'user-read-playback-state',
  'user-modify-playback-state',
  'playlist-read-private',         // ← INDISPENSABLE pour voir TOUTES tes playlists
  'playlist-read-collaborative',   // ← Pour voir les playlists collaboratives où tu es membre
];


export function useSpotifyAuth() {
  // status: checking → logged-out → logging-in → logged-in
  const [status, setStatus] = useState<'checking'|'logged-out'|'logging-in'|'logged-in'>('checking');
  const [error, setError] = useState<string|null>(null);
  const [codeVerifier, setCodeVerifier] = useState<string|null>(null);
  const [refreshKey, setRefreshKey] = useState(0);
  const triggerRefresh = () => setRefreshKey(k => k + 1);

  // 1) Build the PKCE auth request
  const [request, response, promptAsync] = AuthSession.useAuthRequest(
    { clientId, scopes, redirectUri, usePKCE: true },
    { authorizationEndpoint: 'https://accounts.spotify.com/authorize' }
  );

  // 2) On init, check for an existing JWT
  useEffect(() => {
    SecureStore.getItemAsync(JWT_KEY).then(tok => {
      setStatus(tok ? 'logged-in' : 'logged-out');
    });
  }, []);

  // 3) Grab the codeVerifier generated by Expo
  useEffect(() => {
    if (request?.codeVerifier) {
      setCodeVerifier(request.codeVerifier);
    }
  }, [request]);

  // 4) When user hits "login", we move to logging-in → promptAsync()
  const authenticate = async () => {
    setError(null);
    setStatus('logging-in');
    await promptAsync();
  };

  // 5) Handle the redirect back with code
  useEffect(() => {
    if (status !== 'logging-in') return;
    if (response?.type !== 'success' || !response.params.code) return;

    (async () => {
      const code = response.params.code;
      if (!codeVerifier) {
        setError('codeVerifier manquant');
        setStatus('logged-out');
        return;
      }
      try {
        const res = await fetch(`${API_URL}/spotify/spotifyCallback`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ code, code_verifier: codeVerifier }),
        });
        const raw = await res.text();
        let data: any;
        try { data = JSON.parse(raw) }
        catch { throw new Error(`Réponse non-JSON : ${raw.slice(0,120)}`) }

        if (!res.ok || !data.token) {
          throw new Error(data.error ?? `HTTP ${res.status}`);
        }
        await SecureStore.setItemAsync(JWT_KEY, data.token);
        setStatus('logged-in');
        triggerRefresh();
      } catch (e: any) {
        setError(e.message);
        setStatus('logged-out');
      }
    })();
  }, [response, codeVerifier, status]);

  // 6) Logout helper
  const logout = async () => {
    await SecureStore.deleteItemAsync(JWT_KEY);
    setStatus('logged-out');
  };

  // 7) Expose only what’s needed
  const loadingAuth = status === 'checking' || status === 'logging-in';
  const isAuthenticated = status === 'logged-in';

  return useMemo(() => ({
    authenticate,
    logout,
    isAuthenticated,
    loadingAuth,
    errorAuth: error,
    refreshKey,
    triggerRefresh,
  }), [authenticate, logout, isAuthenticated, loadingAuth, error, refreshKey]);
}
